// src/components/P2pSidebarPanel.vue
<!--
  Exodus Browser — sidebar P2P hub (IM, contacts, group, CDN, workspace, calls, collab).
-->
<template>
  <div class="p2p-sidebar">
    <div class="sub-tabs" role="tablist">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        role="tab"
        :class="{ active: subTab === tab.id }"
        @click="subTab = tab.id"
      >
        {{ tab.label }}
      </button>
    </div>

    <div class="panel-body">
      <ImMessenger v-if="subTab === 'im'" @status="forwardStatus" />
      <ContactDirectoryPanel v-else-if="subTab === 'contacts'" @status="forwardStatus" />
      <GroupChatSettings
        v-else-if="subTab === 'chat'"
        :group-id="roomId"
        @status="forwardStatus"
      />
      <P2pCdnSettings v-else-if="subTab === 'cdn'" />
      <FileTransfer v-else-if="subTab === 'workspace'" @status="forwardStatus" />
      <CollaborativeEditing v-else-if="subTab === 'collab'" @status="forwardStatus" />
      <VideoCall v-else-if="subTab === 'call'" @status="forwardStatus" />
      <MeetingRoom v-else-if="subTab === 'meeting'" @status="forwardStatus" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { P2P_TAB_EVENT, type P2pSidebarTab } from '$lib/imChat';
import { logInfo, logDebug } from '@/lib/logger';
import ImMessenger from '@/components/ImMessenger.vue';
import ContactDirectoryPanel from '@/components/ContactDirectoryPanel.vue';
import GroupChatSettings from '@/components/settings/GroupChatSettings.vue';
import P2pCdnSettings from '@/components/settings/P2pCdnSettings.vue';
import FileTransfer from '@/components/FileTransfer.vue';
import CollaborativeEditing from '@/components/CollaborativeEditing.vue';
import VideoCall from '@/components/VideoCall.vue';
import MeetingRoom from '@/components/MeetingRoom.vue';

const props = defineProps<{ roomId?: string }>();
const emit = defineEmits<{ status: [message: string] }>();

const roomId = ref(props.roomId ?? 'lobby');
const subTab = ref<P2pSidebarTab>('im');

const tabs: { id: P2pSidebarTab; label: string }[] = [
  { id: 'im', label: 'WebChat' },
  { id: 'contacts', label: 'Contacts' },
  { id: 'chat', label: 'Group' },
  { id: 'cdn', label: 'CDN' },
  { id: 'workspace', label: 'WorkSpace' },
  { id: 'collab', label: 'Collab' },
  { id: 'call', label: 'Call' },
  { id: 'meeting', label: 'Meeting' },
];

let unsubs: UnlistenFn[] = [];

function forwardStatus(msg: string): void {
  emit('status', msg);
}

function onP2pTabEvent(ev: Event): void {
  const tab = (ev as CustomEvent<P2pSidebarTab>).detail;
  if (tab) subTab.value = tab;
}

onMounted(() => {
  window.addEventListener(P2P_TAB_EVENT, onP2pTabEvent);
  logDebug('P2pSidebarPanel', 'Component mounted, setting up event listeners');
  void (async () => {
    unsubs.push(
      await listen('exodus-focus-im', () => {
        logInfo('P2pSidebarPanel', 'exodus-focus-im event received');
        subTab.value = 'im';
      }),
      await listen('exodus-open-webchat', () => {
        logInfo('P2pSidebarPanel', 'exodus-open-webchat event received');
        subTab.value = 'im';
      }),
    );
    unsubs.push(
      await listen('exodus-focus-workspace', () => {
        logInfo('P2pSidebarPanel', 'exodus-focus-workspace event received');
        subTab.value = 'workspace';
      }),
    );
  })();
});

onUnmounted(() => {
  window.removeEventListener(P2P_TAB_EVENT, onP2pTabEvent);
  for (const u of unsubs) u();
  unsubs = [];
  logDebug('P2pSidebarPanel', 'Component unmounted, event listeners cleaned up');
});
</script>

<style scoped>
.p2p-sidebar {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-height: 0;
  flex: 1;
  height: 100%;
}

.sub-tabs {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.sub-tabs button {
  flex: 1 1 auto;
  min-width: 52px;
  padding: 6px 6px;
  font-size: 11px;
  background: #333;
  border: 1px solid #444;
  border-radius: 6px;
  color: #ccc;
  cursor: pointer;
}

.sub-tabs button.active {
  background: #6366f1;
  border-color: #6366f1;
  color: #fff;
}

.panel-body {
  flex: 1;
  min-height: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
</style>

// src/lib/components/_archive/im/P2pSidebarPanel.svelte
<script lang="ts">
  /**
   * Exodus Browser — sidebar P2P hub (group chat + CDN feed tabs).
   */
  import GroupChatPanel from '$lib/components/GroupChatPanel.svelte';
  import P2pCdnPanel from '$lib/components/P2pCdnPanel.svelte';
  import FileTransfer from '$lib/components/FileTransfer.svelte';
  import ImMessenger from './ImMessenger.svelte';
  import VideoCall from '$lib/components/VideoCall.svelte';
  import MeetingRoom from '$lib/components/MeetingRoom.svelte';
  import ContactDirectory from './ContactDirectory.svelte';
  import RtcCallHost from './RtcCallHost.svelte';
  import { listen } from '@tauri-apps/api/event';
  import { P2P_TAB_EVENT, type P2pSidebarTab } from '$lib/imChat';
  import { onMount } from 'svelte';

  type Props = {
    roomId?: string;
    onStatus: (message: string) => void;
  };

  let { roomId = $bindable('lobby'), onStatus }: Props = $props();

  let subTab = $state<'im' | 'contacts' | 'chat' | 'cdn' | 'workspace' | 'call' | 'meeting'>('im');

  onMount(() => {
    const handler = (ev: Event) => {
      const tab = (ev as CustomEvent<P2pSidebarTab>).detail;
      if (tab) subTab = tab;
    };
    window.addEventListener(P2P_TAB_EVENT, handler);
    const unsubs: Array<() => void> = [];
    void (async () => {
      unsubs.push(
        await listen('exodus-focus-workspace', () => {
          subTab = 'workspace';
        })
      );
      unsubs.push(
        await listen('exodus-focus-im', () => {
          subTab = 'im';
        }),
        await listen('exodus-open-webchat', () => {
          subTab = 'im';
        })
      );
    })();
    return () => {
      window.removeEventListener(P2P_TAB_EVENT, handler);
      for (const u of unsubs) u();
    };
  });
</script>

<div class="p2p-sidebar">
  <RtcCallHost {onStatus} />
  <div class="sub-tabs" role="tablist">
    <button
      type="button"
      role="tab"
      class:active={subTab === 'im'}
      onclick={() => {
        subTab = 'im';
      }}
    >
      WebChat
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'contacts'}
      onclick={() => {
        subTab = 'contacts';
      }}
    >
      Contacts
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'chat'}
      onclick={() => {
        subTab = 'chat';
      }}
    >
      Group
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'cdn'}
      onclick={() => {
        subTab = 'cdn';
      }}
    >
      CDN feed
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'workspace'}
      onclick={() => {
        subTab = 'workspace';
      }}
    >
      WorkSpace
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'call'}
      onclick={() => {
        subTab = 'call';
      }}
    >
      Call
    </button>
    <button
      type="button"
      role="tab"
      class:active={subTab === 'meeting'}
      onclick={() => {
        subTab = 'meeting';
      }}
    >
      Meeting
    </button>
  </div>

  {#if subTab === 'im'}
    <ImMessenger {onStatus} />
  {:else if subTab === 'contacts'}
    <ContactDirectory />
  {:else if subTab === 'chat'}
    <GroupChatPanel bind:groupId={roomId} {onStatus} compact />
  {:else if subTab === 'cdn'}
    <P2pCdnPanel {roomId} {onStatus} compact />
  {:else if subTab === 'workspace'}
    <FileTransfer />
  {:else if subTab === 'call'}
    <VideoCall />
  {:else}
    <MeetingRoom />
  {/if}
</div>

<style>
  .p2p-sidebar {
    display: flex;
    flex-direction: column;
    gap: 8px;
    min-height: 0;
  }

  .sub-tabs {
    display: flex;
    gap: 6px;
  }

  .sub-tabs button {
    flex: 1;
    padding: 6px 8px;
    font-size: 12px;
    background: #333;
    border: 1px solid #444;
    border-radius: 6px;
    color: #ccc;
    cursor: pointer;
  }

  .sub-tabs button.active {
    background: #6366f1;
    border-color: #6366f1;
    color: #fff;
  }
</style>
