// src/components/FindBar.vue
<template>
  <div v-if="open" class="find-bar" role="search">
    <input
      :value="findQuery"
      type="text"
      class="find-input"
      @input="onInput"
      @keydown.enter="$emit('find', 'next')"
      placeholder="Find in page..."
      aria-label="Find in page"
    />
    <span class="find-count" aria-live="polite">
      {{ findResults > 0 ? `${currentFindIndex}/${findResults}` : '0/0' }}
    </span>
    <button 
      type="button" 
      class="find-btn" 
      @click="$emit('find', 'prev')" 
      title="Previous" 
      aria-label="Previous match"
    >
      ▲
    </button>
    <button 
      type="button" 
      class="find-btn" 
      @click="$emit('find', 'next')" 
      title="Next" 
      aria-label="Next match"
    >
      ▼
    </button>
    <button 
      type="button" 
      class="find-btn close" 
      @click="$emit('close')" 
      title="Close" 
      aria-label="Close find bar"
    >
      ×
    </button>
  </div>
</template>

<script setup lang="ts">

interface Props {
  open?: boolean;
  findQuery?: string;
  findResults?: number;
  currentFindIndex?: number;
}

withDefaults(defineProps<Props>(), {
  open: false,
  findQuery: '',
  findResults: 0,
  currentFindIndex: 0,
});

const emit = defineEmits<{
  findInput: [];
  'update:findQuery': [value: string];
  find: [direction?: 'next' | 'prev'];
  close: [];
}>();

function onInput(e: Event): void {
  const value = (e.target as HTMLInputElement).value;
  emit('update:findQuery', value);
  emit('findInput');
}
</script>

<style scoped>
.find-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  background: var(--chrome-toolbar-bg, #dee1e6);
  border-bottom: 1px solid var(--chrome-divider, #dadce0);
}

@media (prefers-color-scheme: dark) {
  .find-bar {
    background: #2d2e30;
    border-color: #5f6368;
  }
}

.find-input {
  flex: 1;
  background: var(--chrome-omnibox-bg, #ffffff);
  border: 1px solid var(--chrome-omnibox-border, #dadce0);
  color: var(--chrome-tab-text-active, #202124);
  padding: 6px 10px;
  border-radius: 16px;
  font-size: 13px;
  min-height: 28px;
}

@media (prefers-color-scheme: dark) {
  .find-input {
    background: #292a2d;
    border-color: #5f6368;
    color: #e8eaed;
  }
}

.find-input:focus {
  outline: none;
  border-color: var(--color-primary, #1a73e8);
  box-shadow: 0 1px 6px rgba(32, 33, 36, 0.28);
}

.find-input::placeholder {
  color: var(--chrome-tab-text, #5f6368);
}

@media (prefers-color-scheme: dark) {
  .find-input::placeholder {
    color: #9aa0a6;
  }
}

.find-count {
  color: var(--chrome-tab-text, #5f6368);
  font-size: 12px;
  min-width: 60px;
  text-align: center;
}

@media (prefers-color-scheme: dark) {
  .find-count {
    color: #9aa0a6;
  }
}

.find-btn {
  background: transparent;
  border: none;
  color: var(--chrome-tab-text, #5f6368);
  width: 28px;
  height: 28px;
  border-radius: 50%;
  cursor: pointer;
  font-size: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background-color 0.15s ease;
}

@media (prefers-color-scheme: dark) {
  .find-btn {
    color: #9aa0a6;
  }
}

.find-btn:hover {
  background: rgba(0, 0, 0, 0.06);
}

@media (prefers-color-scheme: dark) {
  .find-btn:hover {
    background: rgba(255, 255, 255, 0.1);
  }
}

.find-btn.close {
  color: var(--chrome-tab-text, #5f6368);
}

@media (prefers-color-scheme: dark) {
  .find-btn.close {
    color: #9aa0a6;
  }
}

.find-btn.close:hover {
  background: rgba(234, 67, 53, 0.1);
  color: #ea4335;
}
</style>

// src/lib/components/FindBar.svelte
<script lang="ts">
  /**
   * Exodus Browser — in-page find bar (⌘F).
   */
  type Props = {
    open: boolean;
    findQuery: string;
    findResults: number;
    currentFindIndex: number;
    onFindInput: () => void;
    onFind: (direction?: 'next' | 'prev') => void;
    onClose: () => void;
  };

  let {
    open,
    findQuery = $bindable(''),
    findResults,
    currentFindIndex,
    onFindInput,
    onFind,
    onClose,
  }: Props = $props();
</script>

{#if open}
  <div class="find-bar exodus-find-bar" role="search">
    <input
      type="text"
      class="find-input"
      bind:value={findQuery}
      oninput={onFindInput}
      onkeydown={(e) => e.key === 'Enter' && onFind()}
      placeholder="Find in page..."
      aria-label="Find in page"
    />
    <span class="find-count" aria-live="polite">
      {findResults > 0 ? `${currentFindIndex}/${findResults}` : '0/0'}
    </span>
    <button type="button" class="find-btn" onclick={() => onFind('prev')} title="Previous" aria-label="Previous match">▲</button>
    <button type="button" class="find-btn" onclick={() => onFind('next')} title="Next" aria-label="Next match">▼</button>
    <button type="button" class="find-btn close" onclick={onClose} title="Close" aria-label="Close find bar">×</button>
  </div>
{/if}

<style>
  .find-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    background: #2d2d30;
    border-bottom: 1px solid #3c4043;
  }

  .find-input {
    flex: 1;
    background: #202124;
    border: 1px solid #5f6368;
    color: #e8eaed;
    padding: 6px 10px;
    border-radius: 4px;
    font-size: 13px;
  }

  .find-input:focus {
    outline: none;
    border-color: #8ab4f8;
  }

  .find-count {
    color: #9aa0a6;
    font-size: 12px;
    min-width: 60px;
    text-align: center;
  }

  .find-btn {
    background: #3c4043;
    border: 1px solid #5f6368;
    color: #e8eaed;
    width: 28px;
    height: 28px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
  }

  .find-btn:hover {
    background: #4a4d51;
    border-color: #8ab4f8;
  }

  .find-btn.close {
    background: #3c4043;
    color: #9aa0a6;
  }

  .find-btn.close:hover {
    background: #5f6368;
    color: #e8eaed;
  }
</style>
