// src/components/RtcCallHost.vue
<!--
  Exodus Browser — global 1:1 call overlay (incoming/outgoing from any WebChat surface).
-->
<template>
  <RtcCallOverlay
    :open="callOpen"
    :phase="callPhase"
    :peer-name="callPeerName"
    :duration-sec="callDuration"
    :local-stream="localCallStream"
    :remote-stream="remoteCallStream"
    :use-video="useVideo"
    :use-audio="useAudio"
    :on-hangup="() => void hangup()"
    :on-accept="callPhase === 'ringing' && callMgr.sessionId ? () => void acceptCall() : undefined"
    :on-reject="callPhase === 'ringing' ? () => void rejectCall() : undefined"
  />
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import RtcCallOverlay from '@/components/RtcCallOverlay.vue';
import { IM_START_CALL_EVENT, openP2pTab, openWebChat, type ImStartCallDetail } from '$lib/imChat';
import {
  getRtcCallManager,
  type CallSessionCallbacks,
  type CallUiPhase,
} from '$lib/webrtc/rtcCallSession';

const emit = defineEmits<{ status: [message: string] }>();

const callMgr = getRtcCallManager();
const callPhase = ref<CallUiPhase>('idle');
const callPeerName = ref('');
const callDuration = ref(0);
const localCallStream = ref<MediaStream | null>(null);
const remoteCallStream = ref<MediaStream | null>(null);
const useVideo = ref(true);
const useAudio = ref(true);

let timerId: ReturnType<typeof setInterval> | null = null;
let unsubPhase: (() => void) | null = null;

const callOpen = computed(() => callPhase.value !== 'idle');

function callCallbacks(): CallSessionCallbacks {
  return {
    onPhase: (phase) => {
      callPhase.value = phase;
      if (phase === 'connected') {
        callDuration.value = 0;
        if (timerId) clearInterval(timerId);
        timerId = setInterval(() => {
          callDuration.value += 1;
        }, 1000);
      }
      if (phase === 'idle') {
        if (timerId) clearInterval(timerId);
        timerId = null;
        localCallStream.value = null;
        remoteCallStream.value = null;
      }
    },
    onLocalStream: (stream) => {
      localCallStream.value = stream;
    },
    onRemoteStream: (stream) => {
      remoteCallStream.value = stream;
    },
    onIncoming: (name) => {
      callPeerName.value = name;
      openP2pTab('im');
      openWebChat();
      emit('status', `Incoming call from ${name}`);
    },
    onError: (message) => {
      emit('status', message);
    },
  };
}

async function acceptCall(): Promise<void> {
  await callMgr.acceptIncoming(useVideo.value, useAudio.value, callCallbacks());
}

async function rejectCall(): Promise<void> {
  await callMgr.hangup(callCallbacks());
}

async function hangup(): Promise<void> {
  await callMgr.hangup(callCallbacks());
}

function onStartCallEvent(ev: Event): void {
  const detail = (ev as CustomEvent<ImStartCallDetail>).detail;
  if (!detail?.nodeId) return;
  callPeerName.value = detail.name;
  useVideo.value = detail.video;
  useAudio.value = detail.audio;
  openP2pTab('im');
  openWebChat();
  void callMgr.startOutgoing(detail.nodeId, detail.name, detail.video, detail.audio, callCallbacks());
}

onMounted(() => {
  void (async () => {
    try {
      await callMgr.init();
    } catch (e) {
      console.error('[RtcCallHost] Failed to initialize RTC manager:', e);
      // Continue anyway - call features will be disabled
    }
    try {
      await callMgr.listenIncoming(callCallbacks());
    } catch (e) {
      console.error('[RtcCallHost] Failed to listen for incoming calls:', e);
      // Continue anyway - call features will be disabled
    }
  })();
  unsubPhase = callMgr.subscribePhase((phase) => {
    callPhase.value = phase;
  });
  window.addEventListener(IM_START_CALL_EVENT, onStartCallEvent);
});

onUnmounted(() => {
  window.removeEventListener(IM_START_CALL_EVENT, onStartCallEvent);
  unsubPhase?.();
  if (timerId) clearInterval(timerId);
});
</script>

// src/lib/components/RtcCallHost.svelte
<script lang="ts">
  /**
   * Exodus Browser — global 1:1 call overlay (incoming calls on any P2P tab).
   */
  import { onDestroy, onMount } from 'svelte';
  import { IM_START_CALL_EVENT, openP2pTab, type ImStartCallDetail } from '$lib/imChat';
  import {
    getRtcCallManager,
    type CallUiPhase,
  } from '$lib/webrtc/rtcCallSession';
  import RtcCallOverlay from '$lib/components/RtcCallOverlay.svelte';

  type Props = {
    onStatus?: (message: string) => void;
  };

  let { onStatus = () => {} }: Props = $props();

  const callMgr = getRtcCallManager();
  let callPhase = $state<CallUiPhase>('idle');
  let callPeerName = $state('');
  let callDuration = $state(0);
  let localCallStream = $state<MediaStream | null>(null);
  let remoteCallStream = $state<MediaStream | null>(null);
  let useVideo = $state(true);
  let useAudio = $state(true);
  let timerId: ReturnType<typeof setInterval> | null = null;
  let unsubPhase: (() => void) | null = null;

  const callOpen = $derived(callPhase !== 'idle');

  function callCallbacks() {
    return {
      onPhase: (p: CallUiPhase) => {
        callPhase = p;
        if (p === 'connected') {
          callDuration = 0;
          if (timerId) clearInterval(timerId);
          timerId = setInterval(() => {
            callDuration += 1;
          }, 1000);
        }
        if (p === 'idle') {
          if (timerId) clearInterval(timerId);
          timerId = null;
          localCallStream = null;
          remoteCallStream = null;
        }
      },
      onLocalStream: (s: MediaStream | null) => {
        localCallStream = s;
      },
      onRemoteStream: (s: MediaStream | null) => {
        remoteCallStream = s;
      },
      onIncoming: (name: string) => {
        callPeerName = name;
        openP2pTab('im');
        onStatus(`Incoming call from ${name}`);
      },
      onError: (e: string) => onStatus(e),
    };
  }

  async function acceptCall() {
    await callMgr.acceptIncoming(useVideo, useAudio, callCallbacks());
  }

  async function rejectCall() {
    await callMgr.hangup(callCallbacks());
  }

  async function hangup() {
    await callMgr.hangup(callCallbacks());
  }

  function onStartCallEvent(ev: Event) {
    const d = (ev as CustomEvent<ImStartCallDetail>).detail;
    callPeerName = d.name;
    openP2pTab('im');
    void callMgr.startOutgoing(d.nodeId, d.name, d.video, d.audio, callCallbacks());
  }

  onMount(() => {
    void (async () => {
      await callMgr.init();
      await callMgr.listenIncoming(callCallbacks());
    })();
    unsubPhase = callMgr.subscribePhase((p) => {
      callPhase = p;
    });
    window.addEventListener(IM_START_CALL_EVENT, onStartCallEvent);
    return () => {
      window.removeEventListener(IM_START_CALL_EVENT, onStartCallEvent);
    };
  });

  onDestroy(() => {
    unsubPhase?.();
    if (timerId) clearInterval(timerId);
  });
</script>

<RtcCallOverlay
  open={callOpen}
  phase={callPhase}
  peerName={callPeerName}
  durationSec={callDuration}
  localStream={localCallStream}
  remoteStream={remoteCallStream}
  {useVideo}
  {useAudio}
  onHangup={() => void hangup()}
  onAccept={callPhase === 'ringing' && callMgr.sessionId ? () => void acceptCall() : undefined}
  onReject={callPhase === 'ringing' ? () => void rejectCall() : undefined}
/>
