// src/lib/components/InferenceEngineSettings.svelte
<script lang="ts">
  /**
   * Exodus Browser — InferenceEngine registry UI (Tauri `inference_*` commands).
   */
  import { onMount } from 'svelte';
  import {
    inferenceChat,
    inferenceGenerate,
    inferenceGetConfig,
    inferenceGetLoadedModel,
    inferenceGetStats,
    inferenceGetStatus,
    inferenceListModels,
    inferenceLoadModel,
    inferenceUnloadModel,
    type InferenceModelInfo,
  } from '$lib/inferenceClient';

  type Props = {
    aiModel: string;
    onStatus: (message: string) => void;
  };

  let { aiModel, onStatus }: Props = $props();

  let models = $state<InferenceModelInfo[]>([]);
  let loadedModel = $state<string | null>(null);
  let engineStatus = $state('');
  let statsPreview = $state('');
  let configPreview = $state('');
  let selectedModel = $state('');
  let busy = $state(false);
  let testPrompt = $state('Hello from Exodus InferenceEngine');

  async function refresh() {
    busy = true;
    try {
      models = await inferenceListModels();
      loadedModel = await inferenceGetLoadedModel();
      engineStatus = await inferenceGetStatus();
      const stats = await inferenceGetStats();
      statsPreview = JSON.stringify(stats, null, 0).slice(0, 280);
      const cfg = await inferenceGetConfig();
      configPreview = `${cfg.backendType} · max ${cfg.maxTokens} tok · ${cfg.modelPath}`;
      if (!selectedModel && models.length > 0) {
        selectedModel =
          models.find((m) => m.name === aiModel)?.name ??
          models.find((m) => m.loaded)?.name ??
          models[0].name;
      }
    } catch (error) {
      console.error('[Exodus] inference refresh failed:', error);
      onStatus(`Inference engine: ${error}`);
    } finally {
      busy = false;
    }
  }

  async function loadSelected() {
    if (!selectedModel) return;
    busy = true;
    try {
      await inferenceLoadModel(selectedModel);
      onStatus(`Loaded model: ${selectedModel}`);
      await refresh();
    } catch (error) {
      console.error('[Exodus] inference_load_model failed:', error);
      onStatus(`Load model failed: ${error}`);
    } finally {
      busy = false;
    }
  }

  async function unload() {
    busy = true;
    try {
      await inferenceUnloadModel();
      onStatus('Model unloaded');
      await refresh();
    } catch (error) {
      console.error('[Exodus] inference_unload_model failed:', error);
      onStatus(`Unload failed: ${error}`);
    } finally {
      busy = false;
    }
  }

  async function testGenerate() {
    const model = selectedModel || aiModel || 'exodus-default';
    busy = true;
    try {
      const res = await inferenceGenerate({
        model,
        prompt: testPrompt,
        maxTokens: 64,
        stream: false,
      });
      if (res.success && res.text) {
        onStatus(`Generate OK: ${res.text.slice(0, 120)}`);
      } else {
        onStatus(`Generate: ${res.error ?? 'no text'}`);
      }
    } catch (error) {
      console.error('[Exodus] inference_generate failed:', error);
      onStatus(`Generate failed: ${error}`);
    } finally {
      busy = false;
    }
  }

  async function testChat() {
    const model = selectedModel || aiModel || 'exodus-default';
    busy = true;
    try {
      const res = await inferenceChat({
        model,
        messages: [{ role: 'user', content: testPrompt }],
        maxTokens: 64,
        stream: false,
      });
      if (res.success && res.text) {
        onStatus(`Chat OK: ${res.text.slice(0, 120)}`);
      } else {
        onStatus(`Chat: ${res.error ?? 'no text'}`);
      }
    } catch (error) {
      console.error('[Exodus] inference_chat failed:', error);
      onStatus(`Chat failed: ${error}`);
    } finally {
      busy = false;
    }
  }

  $effect(() => {
    if (aiModel && !selectedModel) {
      selectedModel = aiModel;
    }
  });

  onMount(() => {
    void refresh();
  });
</script>

<div class="inference-engine-block">
  <h4>Inference engine (Rust)</h4>
  <p class="settings-hint">
    Registry and routing via Tauri <code>inference_*</code> commands. Uses Allama HTTP when the service is online.
  </p>
  <p class="inference-meta">
    Status: <strong>{engineStatus || '—'}</strong>
    {#if loadedModel}
      · Loaded: <strong>{loadedModel}</strong>
    {/if}
  </p>
  {#if configPreview}
    <p class="inference-meta">{configPreview}</p>
  {/if}
  {#if statsPreview}
    <p class="inference-stats" title={statsPreview}>Stats: {statsPreview}</p>
  {/if}

  <label>
    Registry model
    <select bind:value={selectedModel} disabled={busy || models.length === 0}>
      {#if models.length === 0}
        <option value="">(no models registered)</option>
      {:else}
        {#each models as m (m.name)}
          <option value={m.name}>
            {m.name}{m.loaded ? ' · loaded' : ''} ({m.backend})
          </option>
        {/each}
      {/if}
    </select>
  </label>

  <label>
    Test prompt
    <input type="text" bind:value={testPrompt} disabled={busy} />
  </label>

  <div class="inference-actions">
    <button type="button" class="nav-button secondary" disabled={busy} onclick={() => void refresh()}>
      Refresh
    </button>
    <button type="button" class="nav-button secondary" disabled={busy || !selectedModel} onclick={() => void loadSelected()}>
      Load model
    </button>
    <button type="button" class="nav-button secondary" disabled={busy} onclick={() => void unload()}>
      Unload
    </button>
    <button type="button" class="nav-button secondary" disabled={busy} onclick={() => void testGenerate()}>
      Test generate
    </button>
    <button type="button" class="nav-button secondary" disabled={busy} onclick={() => void testChat()}>
      Test chat
    </button>
  </div>
</div>

<style>
  .inference-engine-block {
    margin-top: 12px;
    padding-top: 12px;
    border-top: 1px solid #333;
  }

  .inference-engine-block h4 {
    margin: 0 0 6px;
    font-size: 13px;
    color: #d1d5db;
  }

  .inference-meta {
    margin: 4px 0;
    font-size: 12px;
    color: #9ca3af;
  }

  .inference-stats {
    margin: 4px 0;
    font-size: 11px;
    color: #6b7280;
    word-break: break-all;
  }

  .inference-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-top: 8px;
  }

  .inference-engine-block label {
    display: block;
    margin-top: 8px;
    font-size: 12px;
    color: #9ca3af;
  }

  .inference-engine-block select,
  .inference-engine-block input {
    display: block;
    width: 100%;
    margin-top: 4px;
    padding: 6px 8px;
    background: #1a1a1a;
    border: 1px solid #404040;
    color: #e5e7eb;
    border-radius: 6px;
    box-sizing: border-box;
  }
</style>

// src/components/settings/InferenceEngineSettings.vue
<!--
  Exodus Browser — InferenceEngine registry settings (Tauri inference_* commands).
-->
<template>
  <section class="settings-section" data-testid="inference-engine-settings">
    <h3>Inference engine</h3>
    <div v-if="loading" class="loading-state">Loading…</div>
    <template v-else>
      <p class="hint">{{ engineStatus || 'Local model runtime' }}</p>
      <label>
        Model
        <select v-model="selectedModel" :disabled="busy" data-testid="inference-model-select">
          <option v-for="m in models" :key="m.name" :value="m.name">{{ m.name }}{{ m.loaded ? ' (loaded)' : '' }}</option>
        </select>
      </label>
      <div class="toolbar">
        <button type="button" class="nav-button secondary" :disabled="busy" @click="() => void refresh()" data-testid="inference-refresh">Refresh</button>
        <button type="button" class="nav-button secondary" :disabled="busy || !selectedModel" @click="() => void loadModel()" data-testid="inference-load">Load</button>
        <button type="button" class="nav-button secondary" :disabled="busy" @click="() => void unloadModel()" data-testid="inference-unload">Unload</button>
      </div>
      <p v-if="statsPreview" class="mono">{{ statsPreview }}</p>
    </template>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import {
  inferenceGetLoadedModel,
  inferenceGetStats,
  inferenceGetStatus,
  inferenceListModels,
  inferenceLoadModel,
  inferenceUnloadModel,
  type InferenceModelInfo,
} from '$lib/inferenceClient';

const props = defineProps<{ aiModel: string }>();
const emit = defineEmits<{
  status: [message: string];
  /** Emitted when user picks a different model (triggers config auto-save). */
  modelChange: [name: string];
}>();

const models = ref<InferenceModelInfo[]>([]);
const selectedModel = ref('');
const engineStatus = ref('');
const statsPreview = ref('');
const busy = ref(false);
const loading = ref(true);

async function refresh(): Promise<void> {
  loading.value = true;
  busy.value = true;
  try {
    models.value = await inferenceListModels();
    const loaded = await inferenceGetLoadedModel();
    engineStatus.value = await inferenceGetStatus();
    const stats = await inferenceGetStats();
    statsPreview.value = JSON.stringify(stats).slice(0, 200);
    if (!selectedModel.value && models.value.length) {
      selectedModel.value =
        models.value.find((m) => m.name === props.aiModel)?.name ??
        models.value.find((m) => m.loaded)?.name ??
        models.value[0].name;
    }
    if (loaded) selectedModel.value = loaded;
  } catch (error) {
    emit('status', `Inference: ${error}`);
  } finally {
    busy.value = false;
    loading.value = false;
  }
}

async function loadModel(): Promise<void> {
  if (!selectedModel.value) return;
  busy.value = true;
  try {
    await inferenceLoadModel(selectedModel.value);
    emit('status', `Loaded ${selectedModel.value}`);
    await refresh();
  } catch (error) {
    emit('status', `Load failed: ${error}`);
  } finally {
    busy.value = false;
  }
}

async function unloadModel(): Promise<void> {
  busy.value = true;
  try {
    await inferenceUnloadModel();
    emit('status', 'Model unloaded');
    await refresh();
  } catch (error) {
    emit('status', `Unload failed: ${error}`);
  } finally {
    busy.value = false;
  }
}

let syncingModelFromParent = false;

watch(
  () => props.aiModel,
  (name) => {
    if (!name || name === selectedModel.value) return;
    syncingModelFromParent = true;
    selectedModel.value = name;
    syncingModelFromParent = false;
  },
);

watch(selectedModel, (name) => {
  if (syncingModelFromParent || !name || name === props.aiModel) return;
  emit('modelChange', name);
});

onMounted(() => void refresh());
</script>

<style scoped>
.hint { font-size: 12px; color: var(--color-text-secondary, #888); }
.toolbar { display: flex; gap: 8px; margin-top: 8px; flex-wrap: wrap; }
.mono { font-size: 11px; word-break: break-all; color: var(--color-text-secondary, #888); }
.nav-button.secondary { padding: 6px 12px; border: none; border-radius: 6px; cursor: pointer; background: var(--color-bg-tertiary, #404040); color: #fff; }
.settings-section h3 { margin: 0 0 12px; font-size: 14px; text-transform: uppercase; color: var(--color-text-secondary, #9ca3af); }
label { display: flex; flex-direction: column; gap: 4px; font-size: 13px; }
.loading-state { padding: 20px; text-align: center; color: var(--color-text-secondary, #9ca3af); }
select { padding: 6px; border-radius: 6px; }
</style>
